# This is how Jekyll knows to use this theme.
remote_theme: tedivm/jekyll-theme-portfolio


title: About Simon Wittber
author: Simon Wittber
email: simonwittber@gmail.com
description: >
  The professional experience of Simon Wittber.


# Header Links - all optional. If set these create header links.
homepage: https://simonwittber.com
github_username: simonwittber
linkedin_username: simonwittber


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme # Lets us test remote themes locally.
